import assert from 'node:assert/strict';
import {mkdir,readFile,writeFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {createRequire} from 'node:module';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const require=createRequire(import.meta.url),{chromium}=require('playwright');
const root=path.dirname(fileURLToPath(import.meta.url)),out=path.join(root,'e2e-evidence');
await mkdir(out,{recursive:true});
const result={surface:'Local browser + actual backend route handlers with disk KV adapter; not hosted evidence',url:'http://127.0.0.1:8787/studio',startedAt:new Date().toISOString(),sourceHashes:{},checks:[],screenshots:[],errors:[],unverified:['Actual hosted Charming permissions and persistent KV','Hosted CSP and download behavior','Other browsers','RTL and localization: this interface is English-only']};
for(const file of ['backend.mjs','ui.js','styles.css','build.mjs','server.mjs','../motion/film.js'])result.sourceHashes[file]=createHash('sha256').update(await readFile(path.join(root,file))).digest('hex');
async function check(name,body){try{const evidence=await body();result.checks.push({name,status:'PASS',evidence});console.log('PASS '+name);}catch(error){result.checks.push({name,status:'FAIL',error:error.message});console.error('FAIL '+name+': '+error.message);}}
const hash=async page=>createHash('sha256').update(await page.locator('#preview').evaluate(canvas=>canvas.toDataURL())).digest('hex');
const state=page=>page.evaluate(()=>({...window.CAVELUX_STUDIO_STATE}));
async function range(page,id,value){await page.locator('#'+id).fill(String(value));await page.locator('#'+id).dispatchEvent('input');}
async function ready(page){await page.goto(result.url);await page.waitForFunction(()=>window.CAVELUX_STUDIO_READY===true);await page.waitForFunction(()=>!document.getElementById('status').textContent.startsWith('Loading'));}
const browser=await chromium.launch({channel:'msedge',headless:true});
let savedName='';
try{
  const context=await browser.newContext({viewport:{width:1440,height:1100},acceptDownloads:true});const page=await context.newPage();page.on('pageerror',error=>result.errors.push(error.message));await ready(page);
  await check('initial state is normal and remains paused',async()=>{const first=await state(page);await page.waitForTimeout(180);const second=await state(page);assert.equal(first.state,'normal');assert.equal(first.playing,false);assert.equal(second.time,first.time);return{first,second};});
  await check('state selection changes actual rendered pixels',async()=>{const normal=await hash(page);await page.locator('#state-working').click();const working=await hash(page);await page.locator('#state-ultracode').click();const ultracode=await hash(page);assert.notEqual(normal,working);assert.notEqual(working,ultracode);assert.equal(await page.locator('#state-ultracode').getAttribute('aria-pressed'),'true');return{normal,working,ultracode};});
  await check('play advances time and pause freezes it',async()=>{await page.locator('#play').click();await page.waitForTimeout(220);const moving=await state(page);assert.equal(moving.playing,true);assert.ok(moving.time>3);await page.locator('#play').click();const stopped=await state(page);await page.waitForTimeout(160);const later=await state(page);assert.equal(later.time,stopped.time);assert.equal(later.playing,false);return{moving,stopped,later};});
  await check('timeline scrub sets exact paused time and wave phase changes pixels',async()=>{await range(page,'timeline',4);const first=await hash(page);assert.equal((await state(page)).time,4);await range(page,'timeline',5);const second=await hash(page);assert.notEqual(first,second);assert.equal((await state(page)).playing,false);return{first,second,time:(await state(page)).time};});
  await check('eye speed changes working eye pixels at the same time',async()=>{await page.locator('#state-working').click();await range(page,'timeline',3.25);await range(page,'eye-speed',0);const still=await hash(page);await range(page,'eye-speed',2);const moving=await hash(page);assert.notEqual(still,moving);assert.equal((await state(page)).eyeSpeed,2);return{still,moving};});
  await check('scale and aura controls alter real canvas output',async()=>{await range(page,'scale',.4);const small=await hash(page);await range(page,'scale',1.4);const large=await hash(page);assert.notEqual(small,large);await page.locator('#aura').uncheck();const clean=await hash(page);assert.notEqual(large,clean);await page.locator('#aura').check();return{small,large,clean};});
  await check('background modes change pixels and transparent corner has zero alpha',async()=>{await page.locator('#background').selectOption('dark');const dark=await hash(page);await page.locator('#background').selectOption('light');const light=await hash(page);assert.notEqual(dark,light);await page.locator('#background').selectOption('transparent');const pixel=await page.locator('#preview').evaluate(canvas=>Array.from(canvas.getContext('2d').getImageData(0,0,1,1).data));assert.equal(pixel[3],0);return{dark,light,transparentCorner:pixel};});
  await check('PNG export downloads a real transparent1080x760 image',async()=>{const event=page.waitForEvent('download');await page.locator('#export-png').click();const download=await event;const target=path.join(out,'export-working.png');await download.saveAs(target);const bytes=await readFile(target);assert.equal(bytes.subarray(1,4).toString(),'PNG');const image=await page.evaluate(async data=>{const img=new Image();img.src=data;await img.decode();const c=document.createElement('canvas');c.width=img.width;c.height=img.height;const g=c.getContext('2d');g.drawImage(img,0,0);return{width:img.width,height:img.height,corner:Array.from(g.getImageData(0,0,1,1).data)};},'data:image/png;base64,'+bytes.toString('base64'));assert.equal(image.width,1080);assert.equal(image.height,760);assert.equal(image.corner[3],0);return{filename:download.suggestedFilename(),bytes:bytes.length,...image};});
  await check('JSON export contains the selected preset settings',async()=>{const expected=await state(page);const event=page.waitForEvent('download');await page.locator('#export-json').click();const download=await event,target=path.join(out,'export-working.json');await download.saveAs(target);const data=JSON.parse(await readFile(target,'utf8'));assert.equal(data.schemaVersion,1);assert.equal(data.settings.state,expected.state);assert.equal(data.settings.eyeSpeed,expected.eyeSpeed);assert.equal(data.settings.background,'transparent');return data;});
  await check('save preset then reload and restore through real disk-backed API',async()=>{
    savedName='Browser evidence '+Date.now();await page.locator('#preset-name').fill(savedName);await page.locator('#save-preset').click();await page.waitForFunction(name=>document.getElementById('status').textContent==='Saved '+name+'.',savedName);
    const expected=await state(page);await page.reload();await page.waitForFunction(()=>window.CAVELUX_STUDIO_READY===true);const load=page.getByRole('button',{name:'Load preset '+savedName,exact:true});await load.waitFor();assert.equal((await state(page)).state,'normal');await load.click();const restored=await state(page);for(const key of ['state','eyeSpeed','scale','background','aura','time'])assert.equal(restored[key],expected[key]);
    const disk=JSON.parse(await readFile(path.join(root,'.local/presets.json'),'utf8'));assert.ok(Object.values(disk).some(preset=>preset.name===savedName));return{expected,restored,diskConfirmed:true};
  });
  await check('write failures show an error and preserve the unsaved look',async()=>{await page.route('**/api/savePreset',route=>route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({ok:false,error:{kind:'operation_failed',message:'Test storage unavailable.'}})}));const before=await state(page);await page.locator('#save-preset').click();await page.waitForFunction(()=>document.getElementById('status').dataset.error==='true');assert.match(await page.locator('#status').innerText(),/Could not save/);assert.deepEqual(await state(page),before);await page.unroute('**/api/savePreset');return{message:await page.locator('#status').innerText(),statePreserved:true};});
  await check('preset deletion persists after reload',async()=>{await page.getByRole('button',{name:'Delete preset '+savedName,exact:true}).click();await page.waitForFunction(name=>document.getElementById('status').textContent==='Deleted '+name+'.',savedName);await page.reload();await page.waitForFunction(()=>window.CAVELUX_STUDIO_READY===true);await page.waitForFunction(()=>!document.getElementById('status').textContent.startsWith('Loading'));assert.equal(await page.getByRole('button',{name:'Load preset '+savedName,exact:true}).count(),0);return{deleted:savedName};});
  await check('read failures remain visible and retry recovers',async()=>{await page.route('**/api/listPresets',route=>route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({ok:false,error:{kind:'operation_failed',message:'Test read unavailable.'}})}));await page.reload();await page.waitForFunction(()=>window.CAVELUX_STUDIO_READY===true);await page.locator('#retry-presets').waitFor({state:'visible'});assert.match(await page.locator('#status').innerText(),/unavailable/i);await page.unroute('**/api/listPresets');await page.locator('#retry-presets').click();await page.locator('#retry-presets').waitFor({state:'hidden'});return{recovered:true};});
  await check('desktop controls are labelled, keyboard reachable and within viewport',async()=>{const labels=await page.locator('button,input,select').evaluateAll(elements=>elements.map(element=>({id:element.id,label:element.getAttribute('aria-label')||element.innerText||element.labels?.[0]?.innerText||'',disabled:element.disabled})));assert.ok(labels.every(item=>item.label.trim()),JSON.stringify(labels));await page.evaluate(()=>{document.activeElement?.blur();window.scrollTo(0,0);});const focused=[];for(let i=0;i<5;i++){await page.keyboard.press('Tab');focused.push(await page.evaluate(()=>({id:document.activeElement.id||document.activeElement.className,visible:document.activeElement.matches(':focus-visible')})));}assert.ok(focused.every(item=>item.visible));const size=await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth}));assert.ok(size.scroll<=size.width);return{labels,focused,size};});
  await page.locator('#state-working').click();await range(page,'timeline',3);await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:path.join(out,'desktop-studio.png'),fullPage:true});result.screenshots.push('desktop-studio.png');
  const mobileContext=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,reducedMotion:'reduce'}),mobile=await mobileContext.newPage();mobile.on('pageerror',error=>result.errors.push(error.message));await ready(mobile);
  await check('mobile reduced-motion starts paused without horizontal overflow',async()=>{const first=await state(mobile);await mobile.waitForTimeout(180);assert.equal((await state(mobile)).time,first.time);assert.equal(first.playing,false);const size=await mobile.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth,reduced:matchMedia('(prefers-reduced-motion: reduce)').matches}));assert.ok(size.scroll<=size.width);assert.equal(size.reduced,true);await mobile.locator('#state-ultracode').click();await range(mobile,'timeline',4);assert.equal((await state(mobile)).state,'ultracode');return{first,size};});
  await mobile.evaluate(()=>window.scrollTo(0,0));await mobile.screenshot({path:path.join(out,'mobile-studio.png'),fullPage:true});result.screenshots.push('mobile-studio.png');
  await check('asset-load failure shows an explicit retry screen',async()=>{await mobile.route('**/assets/06-normal.png',route=>route.fulfill({status:404,body:'Unavailable'}));await mobile.reload();await mobile.locator('#boot-retry').waitFor({state:'visible'});assert.match(await mobile.locator('#boot-error').innerText(),/three uploaded character PNGs/);await mobile.unroute('**/assets/06-normal.png');await mobile.locator('#boot-retry').click();await mobile.waitForFunction(()=>window.CAVELUX_STUDIO_READY===true);return{retryRecovered:true};});
  await check('no uncaught browser errors',async()=>{assert.deepEqual(result.errors,[]);return result.errors;});
  await check('tested source bytes remain current',async()=>{for(const [file,expected]of Object.entries(result.sourceHashes))assert.equal(createHash('sha256').update(await readFile(path.join(root,file))).digest('hex'),expected,file+' changed during test');return result.sourceHashes;});
  await context.close();await mobileContext.close();
}catch(error){result.checks.push({name:'Execution',status:'FAIL',error:error.stack||error.message});console.error(error);}finally{
  await browser.close();result.finishedAt=new Date().toISOString();result.summary={passed:result.checks.filter(item=>item.status==='PASS').length,failed:result.checks.filter(item=>item.status==='FAIL').length};await writeFile(path.join(out,'results.json'),JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result.summary));process.exitCode=result.summary.failed?1:0;
}
