import assert from 'node:assert/strict';
import {mkdir,readFile,writeFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {createRequire} from 'node:module';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const require=createRequire(import.meta.url),{chromium}=require('playwright');
const root=path.dirname(fileURLToPath(import.meta.url)),out=path.join(root,'e2e-evidence');
const result={surface:'Local Edge browser, real reaction renderer and local downloadable files',url:'http://127.0.0.1:8766/reactions/index.html',startedAt:new Date().toISOString(),checks:[],screenshots:[],errors:[],unverified:['Physical iMessage device import or playback','Translated interface: English only; RTL layout is tested separately']};
const ids=['share-break','typing','approved','panic','side-eye','shrug','celebrate','presenting'];
await mkdir(out,{recursive:true});
async function check(name,body){try{const evidence=await body();result.checks.push({name,status:'PASS',evidence});console.log('PASS '+name);}catch(error){result.checks.push({name,status:'FAIL',error:error.message});console.error('FAIL '+name+': '+error.message);}}
const pixelHash=async page=>createHash('sha256').update(Buffer.from(await page.locator('#reaction-preview').evaluate(c=>Array.from(c.getContext('2d').getImageData(0,0,c.width,c.height).data)))).digest('hex');
const current=page=>page.locator('#reaction-time').inputValue();
const browser=await chromium.launch({channel:'msedge',headless:true});
try{
 const context=await browser.newContext({viewport:{width:1440,height:1100},acceptDownloads:true}),page=await context.newPage();page.on('pageerror',e=>result.errors.push(e.message));
 const response=await page.goto(result.url);
 await check('gallery is available as an actual page',async()=>{assert.equal(response.status(),200,'Gallery URL must serve the finished page');assert.equal(await page.getByRole('heading',{name:'A little more character.',exact:true}).count(),1);return{status:response.status()};});
 if(result.checks.at(-1).status==='FAIL')throw new Error('Cannot run gallery flow until the page exists.');
 await page.waitForFunction(()=>window.REACTION_GALLERY_READY===true,{},{timeout:15000});
 await check('all eight reactions are selectable and the first preview is paused',async()=>{assert.deepEqual(await page.locator('[data-reaction]').evaluateAll(nodes=>nodes.map(n=>n.dataset.reaction)),ids);assert.equal(await page.locator('#reaction-play').getAttribute('aria-label'),'Play reaction');const time=await current(page),before=await pixelHash(page);await page.waitForTimeout(150);assert.equal(await current(page),time);assert.equal(await pixelHash(page),before);const pixels=await page.locator('#reaction-preview').evaluate(c=>{const a=c.getContext('2d').getImageData(0,0,c.width,c.height).data;let visible=0;for(let i=3;i<a.length;i+=4)if(a[i])visible++;return{width:c.width,height:c.height,visible};});assert.equal(pixels.width,512);assert.equal(pixels.height,512);assert.ok(pixels.visible>5000);return{time,...pixels};});
 await check('selecting typing changes the visible character and download destinations',async()=>{const before=await pixelHash(page);await page.locator('[data-reaction="typing"]').click();assert.notEqual(await pixelHash(page),before);assert.equal(await page.locator('[data-reaction="typing"]').getAttribute('aria-pressed'),'true');assert.equal(await page.locator('#reaction-title').innerText(),'In the zone');for(const kind of ['gif','mp4','png'])assert.equal(await page.locator('#download-'+kind).getAttribute('href'),'output/typing.'+kind);return{title:await page.locator('#reaction-title').innerText(),time:await current(page)};});
 await check('play advances actual frames and pause freezes them',async()=>{const time=Number(await current(page)),before=await pixelHash(page);await page.locator('#reaction-play').click();await page.waitForTimeout(180);assert.equal(await page.locator('#reaction-play').getAttribute('aria-label'),'Pause reaction');assert.notEqual(await pixelHash(page),before);assert.notEqual(Number(await current(page)),time);await page.locator('#reaction-play').click();const stopped=await pixelHash(page),t=await current(page);await page.waitForTimeout(160);assert.equal(await pixelHash(page),stopped);assert.equal(await current(page),t);return{pausedTime:t};});
 await check('scrubbing chooses an exact paused reaction moment',async()=>{await page.locator('#reaction-time').fill('0.25');await page.locator('#reaction-time').dispatchEvent('input');const first=await pixelHash(page);assert.equal(Number(await current(page)),.25);assert.equal(await page.locator('#reaction-play').getAttribute('aria-label'),'Play reaction');await page.locator('#reaction-time').fill('1.15');await page.locator('#reaction-time').dispatchEvent('input');assert.notEqual(await pixelHash(page),first);assert.equal(Number(await current(page)),1.15);return{time:await current(page)};});
 await check('background controls render transparent, dark and light canvas pixels',async()=>{const samples={};for(const value of ['transparent','dark','light']){await page.locator('#reaction-background').selectOption(value);samples[value]=await page.locator('#reaction-preview').evaluate(c=>Array.from(c.getContext('2d').getImageData(0,0,1,1).data));}assert.equal(samples.transparent[3],0);assert.equal(samples.dark[3],255);assert.equal(samples.light[3],255);assert.notDeepEqual(samples.dark,samples.light);return samples;});
 await check('switching reactions while playing pauses at the selected poster',async()=>{await page.locator('#reaction-play').click();await page.locator('[data-reaction="approved"]').click();assert.equal(await page.locator('#reaction-play').getAttribute('aria-label'),'Play reaction');const observed=Number(await current(page)),catalog=JSON.parse(await readFile(path.join(root,'catalog.json'),'utf8'));assert.equal(observed,catalog.find(r=>r.id==='approved').posterTime);return{time:observed};});
 await check('desktop controls are labelled and keyboard focus is visible',async()=>{const labels=await page.locator('button,input,select').evaluateAll(nodes=>nodes.map(n=>({id:n.id,label:n.getAttribute('aria-label')||n.innerText||n.labels?.[0]?.innerText||''})));assert.ok(labels.every(v=>v.label.trim()));await page.locator('[data-reaction="typing"]').focus();await page.keyboard.press('Enter');assert.equal(await page.locator('[data-reaction="typing"]').getAttribute('aria-pressed'),'true');assert.equal(await page.locator('[data-reaction="typing"]').evaluate(n=>n.matches(':focus-visible')),true);return{labelled:labels.length};});
 await page.locator('#reaction-background').selectOption('dark');await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:path.join(out,'gallery-desktop.png'),fullPage:true});result.screenshots.push('gallery-desktop.png');
 const narrowContext=await browser.newContext({viewport:{width:375,height:812},isMobile:true,hasTouch:true,reducedMotion:'reduce'}),narrow=await narrowContext.newPage();narrow.on('pageerror',e=>result.errors.push(e.message));await narrow.goto(result.url);await narrow.waitForFunction(()=>window.REACTION_GALLERY_READY===true);
 await check('375px reduced-motion view starts paused and has no horizontal overflow',async()=>{const before=await current(narrow);await narrow.waitForTimeout(150);assert.equal(await current(narrow),before);assert.equal(await narrow.locator('#reaction-play').getAttribute('aria-label'),'Play reaction');const size=await narrow.evaluate(()=>({viewport:innerWidth,scroll:document.documentElement.scrollWidth}));assert.ok(size.scroll<=size.viewport);await narrow.locator('[data-reaction="celebrate"]').click();assert.equal(await narrow.locator('[data-reaction="celebrate"]').getAttribute('aria-pressed'),'true');return size;});
 await narrow.evaluate(()=>scrollTo(0,0));await narrow.screenshot({path:path.join(out,'gallery-mobile.png'),fullPage:true});result.screenshots.push('gallery-mobile.png');
 await check('RTL layout retains visible reachable controls without horizontal overflow',async()=>{await narrow.evaluate(()=>{document.documentElement.dir='rtl';});const size=await narrow.evaluate(()=>({viewport:innerWidth,scroll:document.documentElement.scrollWidth,dir:getComputedStyle(document.body).direction}));assert.equal(size.dir,'rtl');assert.ok(size.scroll<=size.viewport);await narrow.locator('[data-reaction="typing"]').focus();await narrow.keyboard.press('Enter');assert.equal(await narrow.locator('[data-reaction="typing"]').getAttribute('aria-pressed'),'true');assert.equal(await narrow.locator('#reaction-play').isVisible(),true);return size;});
 await narrow.evaluate(()=>scrollTo(0,0));await narrow.screenshot({path:path.join(out,'gallery-rtl.png'),fullPage:true});result.screenshots.push('gallery-rtl.png');
 if(process.argv.includes('--skip-downloads')){result.checks.push({name:'Actual rendered download files',status:'SKIP',reason:'Exports are still being rendered; final run must omit --skip-downloads.'});result.unverified.push('Rendered download files not checked in this run');}
 else{
  await check('typing GIF is actually downloaded after selection, playback, pause and scrub',async()=>{await page.locator('[data-reaction="typing"]').click();await page.locator('#reaction-play').click();await page.waitForTimeout(100);await page.locator('#reaction-play').click();await page.locator('#reaction-time').fill('0.5');await page.locator('#reaction-time').dispatchEvent('input');const event=page.waitForEvent('download');await page.locator('#download-gif').click();const download=await event;assert.equal(download.suggestedFilename(),'typing.gif');const dest=path.join(out,'gallery-typing.gif');await download.saveAs(dest);const bytes=await readFile(dest);assert.match(bytes.subarray(0,6).toString(),/^GIF8[79]a$/);return{filename:download.suggestedFilename(),bytes:bytes.length};});
 }
 await check('gallery has no uncaught browser errors',async()=>{assert.deepEqual(result.errors,[]);return result.errors;});
 await context.close();await narrowContext.close();
}catch(error){if(!result.checks.some(c=>c.status==='FAIL'))result.checks.push({name:'Execution',status:'FAIL',error:error.message});}
finally{await browser.close();result.finishedAt=new Date().toISOString();result.summary={passed:result.checks.filter(c=>c.status==='PASS').length,failed:result.checks.filter(c=>c.status==='FAIL').length,skipped:result.checks.filter(c=>c.status==='SKIP').length};await writeFile(path.join(out,process.argv.includes('--red')?'gallery-red-results.json':'gallery-results.json'),JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result.summary));process.exitCode=result.summary.failed?1:0;}
